import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'zadel-001',
    name: 'Noir Tailored Blazer',
    price: 12999,
    originalPrice: 16999,
    discount: 24,
    category: 'Men',
    description:
      'A sharply cut blazer in deep noir wool blend. Structured shoulders, clean lapels, and a refined silhouette designed for boardrooms and evenings alike. Fully lined with subtle gold-tone buttons.',
    sizes: ['S', 'M', 'L', 'XL'],
    images: ['/images/placeholder.svg'],
    featured: true,
    bestSeller: true,
    tags: ['blazer', 'formal', 'wool'],
  },
  {
    id: 'zadel-002',
    name: 'Aether Linen Shirt',
    price: 4499,
    originalPrice: 5999,
    discount: 25,
    category: 'Men',
    description:
      'Breathable Italian linen in pure white. Relaxed yet precise cut with mother-of-pearl buttons and a soft open collar. The essential warm-weather staple elevated to luxury.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: ['/images/placeholder.svg'],
    featured: true,
    bestSeller: true,
    tags: ['shirt', 'linen', 'summer'],
  },
  {
    id: 'zadel-003',
    name: 'Midnight Silk Dress',
    price: 15999,
    originalPrice: 19999,
    discount: 20,
    category: 'Women',
    description:
      'An evening dress cut from fluid black silk. Minimal neckline, elegant drape, and a silhouette that moves with quiet confidence. Lined for comfort without bulk.',
    sizes: ['XS', 'S', 'M', 'L'],
    images: ['/images/placeholder.svg'],
    featured: true,
    bestSeller: true,
    tags: ['dress', 'silk', 'evening'],
  },
  {
    id: 'zadel-004',
    name: 'Cashmere Cloud Sweater',
    price: 9999,
    originalPrice: 12999,
    discount: 23,
    category: 'Women',
    description:
      'Ultra-soft pure cashmere in warm sand. A relaxed crew neck with ribbed cuffs and hem. Lightweight warmth that feels like a second skin.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['/images/placeholder.svg'],
    featured: true,
    bestSeller: false,
    tags: ['sweater', 'cashmere', 'knit'],
  },
  {
    id: 'zadel-005',
    name: 'Obsidian Slim Chinos',
    price: 5499,
    originalPrice: 6999,
    discount: 21,
    category: 'Men',
    description:
      'Navy stretch cotton chinos with a modern slim fit. Clean front, discreet side pockets, and a soft hand-feel that holds its shape through the day.',
    sizes: ['28', '30', '32', '34', '36'],
    images: ['/images/placeholder.svg'],
    featured: false,
    bestSeller: true,
    tags: ['trousers', 'chinos', 'casual'],
  },
  {
    id: 'zadel-006',
    name: 'Ivory Silk Blouse',
    price: 6999,
    originalPrice: 8999,
    discount: 22,
    category: 'Women',
    description:
      'Fluid ivory silk with a soft draped collar and concealed placket. Effortlessly pairs with tailored trousers or evening skirts. Dry-clean only.',
    sizes: ['XS', 'S', 'M', 'L'],
    images: ['/images/placeholder.svg'],
    featured: true,
    bestSeller: false,
    tags: ['blouse', 'silk', 'workwear'],
  },
  {
    id: 'zadel-007',
    name: 'Camel Heritage Overcoat',
    price: 24999,
    originalPrice: 29999,
    discount: 17,
    category: 'Outerwear',
    description:
      'Double-faced camel wool overcoat with a timeless knee length. Notch lapels, deep pockets, and a belt that cinches without bulk. Built to last decades.',
    sizes: ['S', 'M', 'L', 'XL'],
    images: ['/images/placeholder.svg'],
    featured: true,
    bestSeller: true,
    tags: ['coat', 'wool', 'winter'],
  },
  {
    id: 'zadel-008',
    name: 'Noir Leather Boots',
    price: 11999,
    originalPrice: 14999,
    discount: 20,
    category: 'Accessories',
    description:
      'Hand-finished Italian leather ankle boots with a sleek almond toe. Cushioned insole, durable sole, and a silhouette that elevates every look.',
    sizes: ['38', '39', '40', '41', '42', '43'],
    images: ['/images/placeholder.svg'],
    featured: false,
    bestSeller: true,
    tags: ['boots', 'leather', 'footwear'],
  },
  {
    id: 'zadel-009',
    name: 'Merino Turtleneck',
    price: 6499,
    originalPrice: 8499,
    discount: 24,
    category: 'Men',
    description:
      'Fine-gauge merino wool turtleneck in charcoal. Temperature-regulating, itch-free, and refined enough for layering under a blazer or wearing alone.',
    sizes: ['S', 'M', 'L', 'XL'],
    images: ['/images/placeholder.svg'],
    featured: false,
    bestSeller: false,
    tags: ['sweater', 'merino', 'layering'],
  },
  {
    id: 'zadel-010',
    name: 'Field Utility Jacket',
    price: 10999,
    originalPrice: 13999,
    discount: 21,
    category: 'Outerwear',
    description:
      'Structured olive utility jacket in water-resistant cotton-nylon. Clean military lines, hidden pockets, and a modern cropped length for everyday polish.',
    sizes: ['S', 'M', 'L', 'XL'],
    images: ['/images/placeholder.svg'],
    featured: true,
    bestSeller: false,
    tags: ['jacket', 'utility', 'casual'],
  },
  {
    id: 'zadel-011',
    name: 'Crème Fluid Midi Skirt',
    price: 7499,
    originalPrice: 9499,
    discount: 21,
    category: 'Women',
    description:
      'A flowing cream midi skirt in weightless silk blend. Elastic-free waistband with hidden zip, soft A-line drape, and a hem that moves like water.',
    sizes: ['XS', 'S', 'M', 'L'],
    images: ['/images/placeholder.svg'],
    featured: false,
    bestSeller: true,
    tags: ['skirt', 'midi', 'silk'],
  },
  {
    id: 'zadel-012',
    name: 'Gilded Leather Belt',
    price: 3999,
    originalPrice: 4999,
    discount: 20,
    category: 'Accessories',
    description:
      'Full-grain black leather belt with a brushed gold buckle. Slim profile for tailored trousers and dresses. Crafted in small batches.',
    sizes: ['S', 'M', 'L'],
    images: ['/images/placeholder.svg'],
    featured: false,
    bestSeller: false,
    tags: ['belt', 'leather', 'accessory'],
  },
];

export const categories = [
  {
    name: 'Men' as const,
    image: '/images/placeholder-category.svg',
    description: 'Tailored essentials',
  },
  {
    name: 'Women' as const,
    image: '/images/placeholder-category.svg',
    description: 'Refined silhouettes',
  },
  {
    name: 'Outerwear' as const,
    image: '/images/placeholder-category.svg',
    description: 'Seasonal layers',
  },
  {
    name: 'Accessories' as const,
    image: '/images/placeholder-category.svg',
    description: 'Finishing pieces',
  },
];

export function formatINR(amount: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);
}
